### ISSUE TITLE
Docs: add note for view encapsulation

### ISSUE THREAD

**Issue by aamir1995** [meiblorn/ng2-fullpage#94]
Hello! 
It took me about 2 hours to figure out why ng2-fullpage isn't working with my project, Then finally  i changed my `view encapsulation` from `native` to `none` and now it is working perfectly.
Please add a note in docs about `angular 2 view encapsulation`  that it has to be set to `none` before setting ng2-fullpage. :)

**Comment by meiblorn** [comment]
@aamir1995 , you are right. Angular 2 has this issue with styles.

It is already done in [demo app.component.ts](https://github.com/meiblorn/ng2-fullpage/blob/master/demo/app/app.component.ts)

I'll mention this problem in readme.md. Thank you!

**Comment by meiblorn** [comment]
I've updated readme file. Thank you!
